2025-02-20 16:42:02,845 : INFO : root : Loading config.
2025-02-20 16:42:02,847 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-02-20 16:42:02,847 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/0e92bbbc1117f2a7fed5bfc9fd49c3ff.mpf_cache
2025-02-20 16:42:02,861 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/1a4610a235e3724f4c88b7b6a3726c72.mpf_cache
2025-02-20 16:42:02,861 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/9ede27cf5d2808a997283e6386622428.mpf_cache
2025-02-20 16:42:02,861 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/1a4610a235e3724f4c88b7b6a3726c72.mpf_cache
2025-02-20 16:42:02,861 : INFO : ConfigProcessor : Loading config from cache: /var/folders/np/pd6clpgx1xs_0sdwz71m1gyh0000gn/T/911d1b37f4ad2186d44e0f02a423c49c.mpf_cache
2025-02-20 16:42:02,862 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev6
2025-02-20 16:42:02,862 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2025-02-20-16-42-02-mpf-Mac.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': '/Users/andre/Napoleon/logs/2025-02-20-16-42-02-mpf-Mac.log'}
2025-02-20 16:42:02,862 : INFO : Machine : MPF path: /Users/andre/mpf/lib/python3.11/site-packages/mpf
2025-02-20 16:42:02,862 : INFO : Machine : Machine path: /Users/andre/Napoleon
2025-02-20 16:42:02,862 : INFO : Machine : Platform: darwin
2025-02-20 16:42:02,862 : INFO : Machine : Python executable location: /Users/andre/mpf/bin/python3.11
2025-02-20 16:42:02,862 : INFO : Machine : Python version: 3.11.8 (64-bit)
2025-02-20 16:42:02,862 : INFO : Machine : Initializing MPF...
2025-02-20 16:42:02,874 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,877 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-02-20 16:42:02,877 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,877 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,877 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.8', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-15.3.1-arm64-arm-64bit', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '24.3.0', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6020', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'arm64', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/Users/andre/Napoleon/logs/2025-02-20-16-42-02-mpf-Mac.log', 'prev_value': None, 'change': True}
2025-02-20 16:42:02,883 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-02-20 16:42:02,886 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-02-20 16:42:02,887 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...sounds None')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...sounds None')>)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 44, in validate_config_entry
    raise AssertionError(
AssertionError: Invalid settings for player mode_attract_started:sounds None
2025-02-20 16:42:02,887 : INFO : Machine : Starting the main run loop with active modes: []
2025-02-20 16:42:02,887 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-02-20 16:42:02,888 : INFO : Machine : Shutting down...
2025-02-20 16:42:02,888 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-02-20 16:42:03,889 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/core/config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andre/mpf/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 44, in validate_config_entry
    raise AssertionError(
AssertionError: Invalid settings for player mode_attract_started:sounds None
2025-02-20 16:42:03,894 : INFO : root : MPF run loop ended.
